// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WidgetBaseDialog: typeof import('./src/components/dialog/WidgetBaseDialog.vue')['default']
    WidgetCheckboxField: typeof import('./src/components/form/WidgetCheckboxField.vue')['default']
    WidgetColorField: typeof import('./src/components/form/WidgetColorField.vue')['default']
    WidgetDialogTitleBar: typeof import('./src/components/dialog/WidgetDialogTitleBar.vue')['default']
    WidgetEditDialog: typeof import('./src/components/dialog/WidgetEditDialog.vue')['default']
    WidgetSliderField: typeof import('./src/components/form/WidgetSliderField.vue')['default']
    WidgetTimeRangeField: typeof import('./src/components/form/WidgetTimeRangeField.vue')['default']
  }
}
